# Generated by Django 2.2.6 on 2019-12-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Type', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
