# Generated by Django 2.2.6 on 2019-12-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_auto_20191208_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
