# Generated by Django 2.2.6 on 2019-12-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
