# Generated by Django 2.2.6 on 2019-12-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pages', '0007_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Type', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
