# Generated by Django 2.2.6 on 2019-12-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dept',
        ),
    ]
