# Generated by Django 2.2.6 on 2019-12-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pages', '0009_delete_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('Uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Type', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
